LOAD DATA LOCAL INFILE 'Employee.del' INTO TABLE Movie
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Work.del' INTO TABLE Actor
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Company.del' INTO TABLE Actor
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Manage.del' INTO TABLE Actor
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';