LOAD DATA LOCAL INFILE 'Employee.del' INTO TABLE Employee
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Work.del' INTO TABLE Work
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Company.del' INTO TABLE Company
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Manage.del' INTO TABLE Manage
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';
