DROP DATABASE CS143;
CREATE DATABASE CS143;
USE CS143;

CREATE TABLE Employee(
	personname VARCHAR(10) NOT NULL,
	age INT,
	street VARCHAR(10),
	city VARCHAR(10)
);

CREATE TABLE Work(
	personname VARCHAR(10) NOT NULL,
	companyname VARCHAR(10),
	salary INT
);

CREATE TABLE Company(
	companyname VARCHAR(10) NOT NULL,
	city VARCHAR(10)
);

CREATE TABLE Manage(
	personname VARCHAR(10) NOT NULL,
	managername VARCHAR(10)
);

LOAD DATA LOCAL INFILE 'Employee.del' INTO TABLE Employee
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Work.del' INTO TABLE Work
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Company.del' INTO TABLE Company
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Manage.del' INTO TABLE Manage
FIELDS TERMINATED BY ','  OPTIONALLY ENCLOSED BY '"';
